server:
  port: 9001

spring:
  #database-db(spring boot default init dataSource)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.100.100.105:3306/newretaildb?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=round
    username: hno2o
    password: hno2o
    filters: stat
    maxActive: 500
    initialSize: 2
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    maxOpenPreparedStatements: 4
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
#actuator user
  security:
    user:
      name: admin
      password: admin
      roles: ENDPOINT_ADMIN
#actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

mybatis:
  mapperLocations: classpath*:com/junn/newretail/auth/**/mapping/*Mapper.xml
  #plug ComponentScan
  plugComponentScan: com.junn.newretail.auth
  configLocation: classpath:mybatis-config.xml

#database-redis
redis:
  db:
    password: hna2017
    mastername: master1
    sentinels: 192.100.100.107:26379
    PoolConfig:
      maxWaitMillis: 1000
      minIdle: 0
      maxIdle: 100
      maxTotal: 1000

feign:
  hystrix:
    enabled: true
#ribbon rule    
newretail-distributeId: 
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
jwt:
  authUser:
    priKey: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAuD4fne+8tserhGaxxxy4Ud8qYUQy07ZoSy/FEPpMLhi5TkjxKUNK0AfaOV+/bmyfsr98txkenc+LCV3vKJP9KwIDAQABAkEAkFyk+2R4cqNbIkAxNjmrtwLsuw/r33WCnL8OY3IrtMV1slTF0qPuRVaMyaEWtOoZtca8U6r4YLhRTs5rOWTgoQIhAPVofuBfkD+YBh2Y6+ZsTCYHFGyEWCTClfDKbOkh3UbxAiEAwDHQES3+rRwnomnGP3xunyaRiwOXZ0Pl2CrpdKkvHdsCIH3ldrl6rRDC19hVPCgAxOv5U9P77RAmty9JWagcFF2xAiEAkDkRFMM6GHdHOrY7IUrjzCPqFbJFPCWUZcmV1Ihcpf8CIQDMA26YDBF3/tzLMHfrAodzLK17l0Ro6p2bu2FlIkFnpg==
    pubKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALg+H53vvLbHq4RmscccuFHfKmFEMtO2aEsvxRD6TC4YuU5I8SlDStAH2jlfv25sn7K/fLcZHp3Piwld7yiT/SsCAwEAAQ==
    expire: 14400
#图片验证有效期限
code:
  images:
    expire: 300

