server:
  port: 9001

spring:
  #database-db(spring boot default init dataSource)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.100.100.105:3306/TicketDB?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=round
    username: hno2o
    password: hno2o
    filters: stat
    maxActive: 500
    initialSize: 2
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    maxOpenPreparedStatements: 4
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true

management:
  server:
    port: 7001
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
        health:
          show-details: always
